export const localRestaurants = [
  {
    id: 'hdiuRS9sVZSMReZm4oV5SA',
    alias: 'da-andrea-new-york',
    name: 'Da Andrea',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/ZbJxx7Rl8fUH7Pg4GU2p3g/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/da-andrea-new-york?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 1474,
    categories: [
      {
        alias: 'italian',
        title: 'Italian',
      },
      {
        alias: 'mediterranean',
        title: 'Mediterranean',
      },
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.736218,
      longitude: -73.99597,
    },
    transactions: ['restaurant_reservation', 'pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '35 W 13th St',
      address2: '',
      address3: '',
      city: 'New York',
      zip_code: '10011',
      country: 'US',
      state: 'NY',
      display_address: ['35 W 13th St', 'New York, NY 10011'],
    },
    phone: '+12123671979',
    display_phone: '(212) 367-1979',
    distance: 3424.7293369303584,
  },
  {
    id: 'J3NT61-AH5d5Gu5tFJhYSw',
    alias: 'the-cabin-nyc-new-york-2',
    name: 'The Cabin NYC',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/JBz_TO43AqdC2u1JyO_HYQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-cabin-nyc-new-york-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 455,
    categories: [
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
      {
        alias: 'cocktailbars',
        title: 'Cocktail Bars',
      },
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.72393,
      longitude: -73.98383,
    },
    transactions: ['restaurant_reservation', 'pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '205 E 4th St',
      address2: null,
      address3: '',
      city: 'New York',
      zip_code: '10009',
      country: 'US',
      state: 'NY',
      display_address: ['205 E 4th St', 'New York, NY 10009'],
    },
    phone: '+12127770454',
    display_phone: '(212) 777-0454',
    distance: 2240.673403602855,
  },
  {
    id: 'q11TljTQd33XCWlVoPyRqg',
    alias: 'the-osprey-brooklyn',
    name: 'The Osprey',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/2WwMWz2pOA0oHqIkz08shA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-osprey-brooklyn?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 267,
    categories: [
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.702241,
      longitude: -73.995539,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '60 Furman St',
      address2: '',
      address3: null,
      city: 'Brooklyn',
      zip_code: '11201',
      country: 'US',
      state: 'NY',
      display_address: ['60 Furman St', 'Brooklyn, NY 11201'],
    },
    phone: '+13476962505',
    display_phone: '(347) 696-2505',
    distance: 367.7475436977597,
  },
  {
    id: 'fVbUVAiLiGgLA_nxBFxyww',
    alias: 'thursday-kitchen-new-york',
    name: 'Thursday Kitchen',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/kx6lT4K3kNV8ZUauntNQhA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/thursday-kitchen-new-york?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 1599,
    categories: [
      {
        alias: 'korean',
        title: 'Korean',
      },
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
      {
        alias: 'tapasmallplates',
        title: 'Tapas/Small Plates',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.72761,
      longitude: -73.98373,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '424 E 9th St',
      address2: null,
      address3: '',
      city: 'New York',
      zip_code: '10009',
      country: 'US',
      state: 'NY',
      display_address: ['424 E 9th St', 'New York, NY 10009'],
    },
    phone: '',
    display_phone: '',
    distance: 2617.644845204323,
  },
  {
    id: 'MGd6HFEq1ALD58XWNviSXw',
    alias: 'time-out-market-new-york-brooklyn',
    name: 'Time Out Market New York',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/4oRxGWaIhrL7DyRoiEdb7Q/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/time-out-market-new-york-brooklyn?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 383,
    categories: [
      {
        alias: 'food_court',
        title: 'Food Court',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.70342863348067,
      longitude: -73.99214637055226,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '55 Water St',
      address2: '',
      address3: '',
      city: 'Brooklyn',
      zip_code: '11201',
      country: 'US',
      state: 'NY',
      display_address: ['55 Water St', 'Brooklyn, NY 11201'],
    },
    phone: '+19178104855',
    display_phone: '(917) 810-4855',
    distance: 288.11900780114274,
  },
  {
    id: '0CjK3esfpFcxIopebzjFxA',
    alias: 'joes-shanghai-new-york-2',
    name: "Joe's Shanghai",
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/xM4eGRjk_EfSc1V8MdkRXw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/joes-shanghai-new-york-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 6809,
    categories: [
      {
        alias: 'shanghainese',
        title: 'Shanghainese',
      },
      {
        alias: 'seafood',
        title: 'Seafood',
      },
      {
        alias: 'noodles',
        title: 'Noodles',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.7156608,
      longitude: -73.9967012,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '46 Bowery St',
      address2: '',
      address3: '',
      city: 'New York',
      zip_code: '10013',
      country: 'US',
      state: 'NY',
      display_address: ['46 Bowery St', 'New York, NY 10013'],
    },
    phone: '+12122338888',
    display_phone: '(212) 233-8888',
    distance: 1153.9482385806896,
  },
  {
    id: 'jjJc_CrkB2HodEinB6cWww',
    alias: 'lovemama-new-york',
    name: 'LoveMama',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/bLlFKTlVuLfmF-lIDGIjZA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/lovemama-new-york?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 6060,
    categories: [
      {
        alias: 'thai',
        title: 'Thai',
      },
      {
        alias: 'malaysian',
        title: 'Malaysian',
      },
      {
        alias: 'vietnamese',
        title: 'Vietnamese',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.730408722512074,
      longitude: -73.98612673033213,
    },
    transactions: ['restaurant_reservation', 'pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '174 2nd Ave',
      address2: '',
      address3: '',
      city: 'New York',
      zip_code: '10003',
      country: 'US',
      state: 'NY',
      display_address: ['174 2nd Ave', 'New York, NY 10003'],
    },
    phone: '+12122545370',
    display_phone: '(212) 254-5370',
    distance: 2859.902795118878,
  },
  {
    id: '4aF0F8w7yXX9o5_QFky_ig',
    alias: 'celestine-brooklyn',
    name: 'Celestine',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/p98BTWB9IIb4RQyDQw13ZQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/celestine-brooklyn?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 261,
    categories: [
      {
        alias: 'mediterranean',
        title: 'Mediterranean',
      },
      {
        alias: 'bars',
        title: 'Bars',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.704676,
      longitude: -73.987975,
    },
    transactions: ['delivery'],
    price: '$$$',
    location: {
      address1: '1 John St',
      address2: '',
      address3: null,
      city: 'Brooklyn',
      zip_code: '11201',
      country: 'US',
      state: 'NY',
      display_address: ['1 John St', 'Brooklyn, NY 11201'],
    },
    phone: '+17185225356',
    display_phone: '(718) 522-5356',
    distance: 539.4069533813018,
  },
  {
    id: 'hNFe8WhCibrqT4sFcZmAgw',
    alias: 'kong-sihk-tong-港食堂-new-york',
    name: 'Kong Sihk Tong 港食堂',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/u7C6tdCtVgokzEPn5XSQ5A/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/kong-sihk-tong-%E6%B8%AF%E9%A3%9F%E5%A0%82-new-york?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 538,
    categories: [
      {
        alias: 'chinese',
        title: 'Chinese',
      },
      {
        alias: 'hkcafe',
        title: 'Hong Kong Style Cafe',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.715433714742154,
      longitude: -73.9981186386701,
    },
    transactions: ['pickup', 'delivery'],
    price: '$',
    location: {
      address1: '65 Bayard St',
      address2: '',
      address3: null,
      city: 'New York',
      zip_code: '10013',
      country: 'US',
      state: 'NY',
      display_address: ['65 Bayard St', 'New York, NY 10013'],
    },
    phone: '+16468506140',
    display_phone: '(646) 850-6140',
    distance: 1156.5626748255393,
  },
  {
    id: '8SehQovJOuQDLbtzLLYLyw',
    alias: 'rh-rooftop-restaurant-new-york-new-york-2',
    name: 'RH Rooftop Restaurant New York',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/qNQTyRt8yeJ8q9Tzc2BBLA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/rh-rooftop-restaurant-new-york-new-york-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 641,
    categories: [
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
      {
        alias: 'wine_bars',
        title: 'Wine Bars',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.73985,
      longitude: -74.00639,
    },
    transactions: [],
    price: '$$$',
    location: {
      address1: '9 9th Ave',
      address2: null,
      address3: '',
      city: 'New York',
      zip_code: '10014',
      country: 'US',
      state: 'NY',
      display_address: ['9 9th Ave', 'New York, NY 10014'],
    },
    phone: '+12122172210',
    display_phone: '(212) 217-2210',
    distance: 3959.1646378131454,
  },
  {
    id: '4DInnPhOyvXFbYpUdO0SMQ',
    alias: 'antidote-brooklyn-2',
    name: 'Antidote',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/BLX5aFrPlJShwvee1vh7ug/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/antidote-brooklyn-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 135,
    categories: [
      {
        alias: 'cocktailbars',
        title: 'Cocktail Bars',
      },
      {
        alias: 'dimsum',
        title: 'Dim Sum',
      },
      {
        alias: 'szechuan',
        title: 'Szechuan',
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 40.714253413118925,
      longitude: -73.96544806659222,
    },
    transactions: ['pickup', 'delivery'],
    location: {
      address1: '66 S 2nd St',
      address2: '',
      address3: null,
      city: 'Brooklyn',
      zip_code: '11249',
      country: 'US',
      state: 'NY',
      display_address: ['66 S 2nd St', 'Brooklyn, NY 11249'],
    },
    phone: '+17187822585',
    display_phone: '(718) 782-2585',
    distance: 2621.1806649593627,
  },
  {
    id: 'ysqgdbSrezXgVwER2kQWKA',
    alias: 'julianas-brooklyn-3',
    name: "Juliana's",
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/j6Hoc_YpJJapUUzfd9pj8A/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/julianas-brooklyn-3?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 2496,
    categories: [
      {
        alias: 'pizza',
        title: 'Pizza',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.70274718768062,
      longitude: -73.99343490196397,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '19 Old Fulton St',
      address2: '',
      address3: '',
      city: 'Brooklyn',
      zip_code: '11201',
      country: 'US',
      state: 'NY',
      display_address: ['19 Old Fulton St', 'Brooklyn, NY 11201'],
    },
    phone: '+17185966700',
    display_phone: '(718) 596-6700',
    distance: 308.56984360837544,
  },
  {
    id: 'FlZ1zdVEKWv7dwqm8Uw8-w',
    alias: 'raku-new-york-7',
    name: 'Raku',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/GEbZnH1jR4n7D5WOJ3urPg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/raku-new-york-7?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 1351,
    categories: [
      {
        alias: 'japanese',
        title: 'Japanese',
      },
      {
        alias: 'noodles',
        title: 'Noodles',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.7264988089246,
      longitude: -73.9866526052356,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '342 E 6th St',
      address2: '',
      address3: '',
      city: 'New York',
      zip_code: '10003',
      country: 'US',
      state: 'NY',
      display_address: ['342 E 6th St', 'New York, NY 10003'],
    },
    phone: '+12122281324',
    display_phone: '(212) 228-1324',
    distance: 2428.0392489129867,
  },
  {
    id: 'uoT2_Wrt1noD6kZOID7tUg',
    alias: 'jane-restaurant-new-york',
    name: 'Jane Restaurant',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/jTGzYyowSV-4n3WoM0GZKQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/jane-restaurant-new-york?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 3388,
    categories: [
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
      {
        alias: 'bars',
        title: 'Bars',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.7273779,
      longitude: -74.00025,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '100 W Houston St',
      address2: '',
      address3: '',
      city: 'New York',
      zip_code: '10012',
      country: 'US',
      state: 'NY',
      display_address: ['100 W Houston St', 'New York, NY 10012'],
    },
    phone: '+12122547000',
    display_phone: '(212) 254-7000',
    distance: 2489.9758210239006,
  },
  {
    id: 'Me4TxTbPPQZQopW1wOGx5g',
    alias: 'jacks-wife-freda-new-york',
    name: "Jack's Wife Freda",
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/Ll_WSepPlmUwyxsjU4dlUA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/jacks-wife-freda-new-york?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 2162,
    categories: [
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
      {
        alias: 'mediterranean',
        title: 'Mediterranean',
      },
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.7221323,
      longitude: -73.9975402,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '226 Lafayette St',
      address2: '',
      address3: '',
      city: 'New York',
      zip_code: '10012',
      country: 'US',
      state: 'NY',
      display_address: ['226 Lafayette St', 'New York, NY 10012'],
    },
    phone: '+12125108550',
    display_phone: '(212) 510-8550',
    distance: 1875.6283558031143,
  },
  {
    id: 'qEe7nIhPfEL6L0-VYhWRrA',
    alias: 'raku-new-york-6',
    name: 'Raku',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/F27q2Tq72amfU1iyq1AOyg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/raku-new-york-6?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 698,
    categories: [
      {
        alias: 'japanese',
        title: 'Japanese',
      },
      {
        alias: 'noodles',
        title: 'Noodles',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.72728,
      longitude: -74.00252,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '48 Macdougal St',
      address2: null,
      address3: '',
      city: 'New York',
      zip_code: '10012',
      country: 'US',
      state: 'NY',
      display_address: ['48 Macdougal St', 'New York, NY 10012'],
    },
    phone: '+12129894797',
    display_phone: '(212) 989-4797',
    distance: 2522.2670460297,
  },
  {
    id: '16ZnHpuaaBt92XWeJHCC5A',
    alias: 'olio-e-più-new-york-7',
    name: 'Olio e Più',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/tQlfEiPaj2SUg-N2NnDsrA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/olio-e-pi%C3%B9-new-york-7?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 3468,
    categories: [
      {
        alias: 'pizza',
        title: 'Pizza',
      },
      {
        alias: 'italian',
        title: 'Italian',
      },
      {
        alias: 'cocktailbars',
        title: 'Cocktail Bars',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.733798036104304,
      longitude: -73.99977392649927,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '3 Greenwich Ave',
      address2: null,
      address3: '',
      city: 'New York',
      zip_code: '10014',
      country: 'US',
      state: 'NY',
      display_address: ['3 Greenwich Ave', 'New York, NY 10014'],
    },
    phone: '+12122436546',
    display_phone: '(212) 243-6546',
    distance: 3186.3804982206075,
  },
  {
    id: 'AIKjw2QLvVNdha3TciJYzg',
    alias: 'boqueria-soho-new-york-2',
    name: 'Boqueria Soho',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/4G0jDG2jEZXYoOshlBtc7A/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/boqueria-soho-new-york-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 1174,
    categories: [
      {
        alias: 'spanish',
        title: 'Spanish',
      },
      {
        alias: 'tapas',
        title: 'Tapas Bars',
      },
      {
        alias: 'tapasmallplates',
        title: 'Tapas/Small Plates',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.7249227818105,
      longitude: -74.00215536627918,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '171 Spring St',
      address2: '',
      address3: '',
      city: 'New York',
      zip_code: '10012',
      country: 'US',
      state: 'NY',
      display_address: ['171 Spring St', 'New York, NY 10012'],
    },
    phone: '+12123434255',
    display_phone: '(212) 343-4255',
    distance: 2264.9413642445584,
  },
  {
    id: 'axqp3pGJXnTLgq2QrPyDyQ',
    alias: 'benemon-new-york',
    name: 'Benemon',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/5ZRHsFgkyoSzac8ofvhvvg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/benemon-new-york?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 661,
    categories: [
      {
        alias: 'japanese',
        title: 'Japanese',
      },
      {
        alias: 'tapasmallplates',
        title: 'Tapas/Small Plates',
      },
      {
        alias: 'bars',
        title: 'Bars',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 40.72551,
      longitude: -73.98838,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '108 E 4th St',
      address2: null,
      address3: '',
      city: 'New York',
      zip_code: '10003',
      country: 'US',
      state: 'NY',
      display_address: ['108 E 4th St', 'New York, NY 10003'],
    },
    phone: '+12126143006',
    display_phone: '(212) 614-3006',
    distance: 2289.2038585586733,
  },
  {
    id: 'SWK0AQ5KTDDCt8AtOhhasg',
    alias: 'malibu-farm-new-york-new-york-2',
    name: 'Malibu Farm New York',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/7YOapY_XQTw7HclbVyz55A/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/malibu-farm-new-york-new-york-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
    review_count: 288,
    categories: [
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
      {
        alias: 'venues',
        title: 'Venues & Event Spaces',
      },
      {
        alias: 'beer_and_wine',
        title: 'Beer, Wine & Spirits',
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 40.70634,
      longitude: -74.00383,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '89 South St',
      address2: 'Pier 17',
      address3: null,
      city: 'New York',
      zip_code: '10038',
      country: 'US',
      state: 'NY',
      display_address: ['89 South St', 'Pier 17', 'New York, NY 10038'],
    },
    phone: '+12122653030',
    display_phone: '(212) 265-3030',
    distance: 619.5268971577544,
  },
];
// [
//   {
//     id: '8VurRDEj1RpimenhgTmyFQ',
//     alias: 'kaiyō-rooftop-san-francisco-5',
//     name: 'KAIYŌ Rooftop',
//     image_url:
//       'https://s3-media4.fl.yelpcdn.com/bphoto/IpnkGDpsm94wGzTAdFekPg/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/kaiy%C5%8D-rooftop-san-francisco-5?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 265,
//     categories: [
//       {
//         alias: 'peruvian',
//         title: 'Peruvian',
//       },
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//       {
//         alias: 'sushi',
//         title: 'Sushi Bars',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.77882,
//       longitude: -122.3924,
//     },
//     transactions: [],
//     location: {
//       address1: '701 3rd St',
//       address2: 'Fl 12',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94105',
//       country: 'US',
//       state: 'CA',
//       display_address: ['701 3rd St', 'Fl 12', 'San Francisco, CA 94105'],
//     },
//     phone: '',
//     display_phone: '',
//     distance: 4355.096615628698,
//   },
//   {
//     id: 'J7_-faNq_Ag9qTOlDn81Pw',
//     alias: 'starbelly-san-francisco',
//     name: 'Starbelly',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/G1SweY3VbKx_BqAws9RytA/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/starbelly-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 2076,
//     categories: [
//       {
//         alias: 'comfortfood',
//         title: 'Comfort Food',
//       },
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//       {
//         alias: 'wine_bars',
//         title: 'Wine Bars',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.76402,
//       longitude: -122.43253,
//     },
//     transactions: ['delivery', 'restaurant_reservation', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '3583 16th St',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94114',
//       country: 'US',
//       state: 'CA',
//       display_address: ['3583 16th St', 'San Francisco, CA 94114'],
//     },
//     phone: '+14152527500',
//     display_phone: '(415) 252-7500',
//     distance: 490.0201155034338,
//   },
//   {
//     id: 'LPoRD0huneBqPZbg1wsJ_Q',
//     alias: 'jamies-place-san-francisco',
//     name: "Jamie's place",
//     image_url:
//       'https://s3-media3.fl.yelpcdn.com/bphoto/RKaMazQvvf_AEoFKqquESg/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/jamies-place-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 218,
//     categories: [
//       {
//         alias: 'asianfusion',
//         title: 'Asian Fusion',
//       },
//       {
//         alias: 'newamerican',
//         title: 'American (New)',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.762616,
//       longitude: -122.465979,
//     },
//     transactions: ['delivery', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '1380 9th Ave',
//       address2: null,
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94122',
//       country: 'US',
//       state: 'CA',
//       display_address: ['1380 9th Ave', 'San Francisco, CA 94122'],
//     },
//     phone: '+14158031888',
//     display_phone: '(415) 803-1888',
//     distance: 2612.178424720017,
//   },
//   {
//     id: 'HHtpR0RslupSQ99GIIwW5A',
//     alias: 'marufuku-ramen-san-francisco-5',
//     name: 'Marufuku Ramen',
//     image_url:
//       'https://s3-media4.fl.yelpcdn.com/bphoto/ouK2VmW0SrI70jsJpTxJhw/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/marufuku-ramen-san-francisco-5?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 3975,
//     categories: [
//       {
//         alias: 'ramen',
//         title: 'Ramen',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.78511637816802,
//       longitude: -122.43200834862841,
//     },
//     transactions: ['delivery', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '1581 Webster St',
//       address2: 'Ste 235',
//       address3: null,
//       city: 'San Francisco',
//       zip_code: '94115',
//       country: 'US',
//       state: 'CA',
//       display_address: [
//         '1581 Webster St',
//         'Ste 235',
//         'San Francisco, CA 94115',
//       ],
//     },
//     phone: '+14158729786',
//     display_phone: '(415) 872-9786',
//     distance: 2720.9187117007004,
//   },
//   {
//     id: '_hOVIgjVRl_HzvLaa65KJg',
//     alias: 'the-snug-san-francisco',
//     name: 'The Snug',
//     image_url:
//       'https://s3-media3.fl.yelpcdn.com/bphoto/MutHRQoBt5krVldjIK88IA/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/the-snug-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 320,
//     categories: [
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//       {
//         alias: 'newamerican',
//         title: 'American (New)',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.79094,
//       longitude: -122.43443,
//     },
//     transactions: ['delivery'],
//     price: '$$',
//     location: {
//       address1: '2301 Fillmore St',
//       address2: '',
//       address3: null,
//       city: 'San Francisco',
//       zip_code: '94115',
//       country: 'US',
//       state: 'CA',
//       display_address: ['2301 Fillmore St', 'San Francisco, CA 94115'],
//     },
//     phone: '',
//     display_phone: '',
//     distance: 3342.887795851584,
//   },
//   {
//     id: 'lUUQi1b2rV3glIn4t2I1Iw',
//     alias: 'horsefeather-san-francisco-2',
//     name: 'Horsefeather',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/Fh0PkCrPfP7mItoZvVG2VA/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/horsefeather-san-francisco-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 437,
//     categories: [
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//       {
//         alias: 'newamerican',
//         title: 'American (New)',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.774501,
//       longitude: -122.437355,
//     },
//     transactions: ['delivery', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '528 Divisidero St',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94117',
//       country: 'US',
//       state: 'CA',
//       display_address: ['528 Divisidero St', 'San Francisco, CA 94117'],
//     },
//     phone: '+14158171939',
//     display_phone: '(415) 817-1939',
//     distance: 1514.8624498232032,
//   },
//   {
//     id: '8kck3-K4zYKTJbJko0JlXQ',
//     alias: 'farmhouse-kitchen-thai-cuisine-san-francisco',
//     name: 'Farmhouse Kitchen Thai Cuisine',
//     image_url:
//       'https://s3-media4.fl.yelpcdn.com/bphoto/kUlEaPpv0JGlHG_nrPr7wQ/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/farmhouse-kitchen-thai-cuisine-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 3293,
//     categories: [
//       {
//         alias: 'thai',
//         title: 'Thai',
//       },
//       {
//         alias: 'comfortfood',
//         title: 'Comfort Food',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.760192883932795,
//       longitude: -122.4114188698492,
//     },
//     transactions: ['delivery', 'restaurant_reservation', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '710 Florida St',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94110',
//       country: 'US',
//       state: 'CA',
//       display_address: ['710 Florida St', 'San Francisco, CA 94110'],
//     },
//     phone: '+14158142920',
//     display_phone: '(415) 814-2920',
//     distance: 2201.588555604964,
//   },
//   {
//     id: '-DrR38H1Abk0wCyu9XOLug',
//     alias: 'sweet-maple-san-francisco',
//     name: 'Sweet Maple',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/etyS0Af-PS74CTwxly2uoA/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/sweet-maple-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 4334,
//     categories: [
//       {
//         alias: 'tradamerican',
//         title: 'American (Traditional)',
//       },
//       {
//         alias: 'breakfast_brunch',
//         title: 'Breakfast & Brunch',
//       },
//       {
//         alias: 'burgers',
//         title: 'Burgers',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.785735681426,
//       longitude: -122.43507770852,
//     },
//     transactions: ['delivery', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '2101 Sutter St',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94115',
//       country: 'US',
//       state: 'CA',
//       display_address: ['2101 Sutter St', 'San Francisco, CA 94115'],
//     },
//     phone: '+14156559169',
//     display_phone: '(415) 655-9169',
//     distance: 2764.2882648857435,
//   },
//   {
//     id: 'f-m7-hyFzkf0HSEeQ2s-9A',
//     alias: 'fog-harbor-fish-house-san-francisco-2',
//     name: 'Fog Harbor Fish House',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/by8Hh63BLPv_HUqRUdsp_w/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/fog-harbor-fish-house-san-francisco-2?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 8023,
//     categories: [
//       {
//         alias: 'seafood',
//         title: 'Seafood',
//       },
//       {
//         alias: 'wine_bars',
//         title: 'Wine Bars',
//       },
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.80898821475503,
//       longitude: -122.41029651587517,
//     },
//     transactions: ['restaurant_reservation'],
//     price: '$$',
//     location: {
//       address1: '39 Pier',
//       address2: 'Ste a - 202',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94133',
//       country: 'US',
//       state: 'CA',
//       display_address: ['39 Pier', 'Ste a - 202', 'San Francisco, CA 94133'],
//     },
//     phone: '+14159692010',
//     display_phone: '(415) 969-2010',
//     distance: 5820.143221179387,
//   },
//   {
//     id: '8dUaybEPHsZMgr1iKgqgMQ',
//     alias: 'sotto-mare-san-francisco-4',
//     name: 'Sotto Mare',
//     image_url:
//       'https://s3-media3.fl.yelpcdn.com/bphoto/o3hIcGLMxV_5ynxEjGWGrw/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/sotto-mare-san-francisco-4?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 4505,
//     categories: [
//       {
//         alias: 'seafood',
//         title: 'Seafood',
//       },
//       {
//         alias: 'italian',
//         title: 'Italian',
//       },
//       {
//         alias: 'bars',
//         title: 'Bars',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.79979,
//       longitude: -122.40834,
//     },
//     transactions: ['delivery', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '552 Green St',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94133',
//       country: 'US',
//       state: 'CA',
//       display_address: ['552 Green St', 'San Francisco, CA 94133'],
//     },
//     phone: '+14153983181',
//     display_phone: '(415) 398-3181',
//     distance: 4970.484877370465,
//   },
//   {
//     id: 'ttarnopezxmp2ROB1N2PaA',
//     alias: 'nopa-san-francisco',
//     name: 'Nopa',
//     image_url:
//       'https://s3-media4.fl.yelpcdn.com/bphoto/QOc_docjeCrDHlckTaDE2A/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/nopa-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 5259,
//     categories: [
//       {
//         alias: 'newamerican',
//         title: 'American (New)',
//       },
//       {
//         alias: 'desserts',
//         title: 'Desserts',
//       },
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.77483,
//       longitude: -122.43746,
//     },
//     transactions: ['delivery'],
//     price: '$$$',
//     location: {
//       address1: '560 Divisadero St',
//       address2: null,
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94117',
//       country: 'US',
//       state: 'CA',
//       display_address: ['560 Divisadero St', 'San Francisco, CA 94117'],
//     },
//     phone: '+14158648643',
//     display_phone: '(415) 864-8643',
//     distance: 1559.1831881623302,
//   },
//   {
//     id: 'd5752S_RDb26HxoL6O06eQ',
//     alias: 'beit-rima-san-francisco-4',
//     name: 'Beit Rima',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/M_-YjU1xtWfYP_oLsznIBw/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/beit-rima-san-francisco-4?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 187,
//     categories: [
//       {
//         alias: 'arabian',
//         title: 'Arabic',
//       },
//       {
//         alias: 'mediterranean',
//         title: 'Mediterranean',
//       },
//       {
//         alias: 'lebanese',
//         title: 'Lebanese',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.765956,
//       longitude: -122.449679,
//     },
//     transactions: [],
//     price: '$$',
//     location: {
//       address1: '86 Carl St',
//       address2: '',
//       address3: null,
//       city: 'San Francisco',
//       zip_code: '94117',
//       country: 'US',
//       state: 'CA',
//       display_address: ['86 Carl St', 'San Francisco, CA 94117'],
//     },
//     phone: '+14155661274',
//     display_phone: '(415) 566-1274',
//     distance: 1291.888183200842,
//   },
//   {
//     id: 'AtFGQccBpgEZzsy9V1330Q',
//     alias: 'lily-san-francisco',
//     name: 'Lily',
//     image_url:
//       'https://s3-media3.fl.yelpcdn.com/bphoto/y80_nZ_LfLw5AZip8L-MEg/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/lily-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 249,
//     categories: [
//       {
//         alias: 'vietnamese',
//         title: 'Vietnamese',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.782826,
//       longitude: -122.461686,
//     },
//     transactions: ['delivery', 'pickup'],
//     location: {
//       address1: '225 Clement St',
//       address2: null,
//       address3: null,
//       city: 'San Francisco',
//       zip_code: '94118',
//       country: 'US',
//       state: 'CA',
//       display_address: ['225 Clement St', 'San Francisco, CA 94118'],
//     },
//     phone: '+14157425285',
//     display_phone: '(415) 742-5285',
//     distance: 3299.107317666393,
//   },
//   {
//     id: 'gqVl3RprESEqkIPeJH0yOg',
//     alias: 'zazie-san-francisco',
//     name: 'Zazie',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/p-wLlWtS6hcPY5vXWkd92Q/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/zazie-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 4881,
//     categories: [
//       {
//         alias: 'breakfast_brunch',
//         title: 'Breakfast & Brunch',
//       },
//       {
//         alias: 'french',
//         title: 'French',
//       },
//       {
//         alias: 'wine_bars',
//         title: 'Wine Bars',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.765244,
//       longitude: -122.4501138,
//     },
//     transactions: ['delivery', 'restaurant_reservation'],
//     price: '$$',
//     location: {
//       address1: '941 Cole St',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94117',
//       country: 'US',
//       state: 'CA',
//       display_address: ['941 Cole St', 'San Francisco, CA 94117'],
//     },
//     phone: '+14155645332',
//     display_phone: '(415) 564-5332',
//     distance: 1294.8624343961546,
//   },
//   {
//     id: 'XQLmEdXoMzOpffwoFaBtaQ',
//     alias: 'kitchen-story-san-francisco',
//     name: 'Kitchen Story',
//     image_url:
//       'https://s3-media3.fl.yelpcdn.com/bphoto/NFhzbxcz4No5Ny8_IHdPMw/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/kitchen-story-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 3787,
//     categories: [
//       {
//         alias: 'breakfast_brunch',
//         title: 'Breakfast & Brunch',
//       },
//       {
//         alias: 'asianfusion',
//         title: 'Asian Fusion',
//       },
//       {
//         alias: 'newamerican',
//         title: 'American (New)',
//       },
//     ],
//     rating: 4.0,
//     coordinates: {
//       latitude: 37.764290777795395,
//       longitude: -122.43072410226956,
//     },
//     transactions: ['delivery', 'restaurant_reservation', 'pickup'],
//     price: '$$',
//     location: {
//       address1: '3499 16th St',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94114',
//       country: 'US',
//       state: 'CA',
//       display_address: ['3499 16th St', 'San Francisco, CA 94114'],
//     },
//     phone: '+14155254905',
//     display_phone: '(415) 525-4905',
//     distance: 628.7327818809532,
//   },
//   {
//     id: 'qfRZjzNqO3fRgEGqvGNY-A',
//     alias: 'santeria-san-francisco',
//     name: 'Santeria',
//     image_url:
//       'https://s3-media4.fl.yelpcdn.com/bphoto/cBh6Ih-cKY0YRVmRPaIGHA/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/santeria-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 202,
//     categories: [
//       {
//         alias: 'mexican',
//         title: 'Mexican',
//       },
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.764836,
//       longitude: -122.431808,
//     },
//     transactions: ['restaurant_reservation'],
//     price: '$$',
//     location: {
//       address1: '2251 Market St',
//       address2: '',
//       address3: null,
//       city: 'San Francisco',
//       zip_code: '94114',
//       country: 'US',
//       state: 'CA',
//       display_address: ['2251 Market St', 'San Francisco, CA 94114'],
//     },
//     phone: '+14158964496',
//     display_phone: '(415) 896-4496',
//     distance: 603.8917617486115,
//   },
//   {
//     id: 'iXoLJWjbcXCO43RT-H0uQQ',
//     alias: 'jaranita-san-francisco-4',
//     name: 'Jaranita',
//     image_url:
//       'https://s3-media3.fl.yelpcdn.com/bphoto/jgM34JZztq7h1LU1zoUuUg/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/jaranita-san-francisco-4?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 309,
//     categories: [
//       {
//         alias: 'peruvian',
//         title: 'Peruvian',
//       },
//       {
//         alias: 'latin',
//         title: 'Latin American',
//       },
//       {
//         alias: 'cocktailbars',
//         title: 'Cocktail Bars',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.80024,
//       longitude: -122.437539,
//     },
//     transactions: ['delivery', 'restaurant_reservation', 'pickup'],
//     location: {
//       address1: '3340 Steiner St',
//       address2: null,
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94123',
//       country: 'US',
//       state: 'CA',
//       display_address: ['3340 Steiner St', 'San Francisco, CA 94123'],
//     },
//     phone: '+14156559585',
//     display_phone: '(415) 655-9585',
//     distance: 4375.67008536983,
//   },
//   {
//     id: 'ATj-8RmOJln9UnCEuraEzw',
//     alias: 'noodle-in-a-haystack-san-francisco',
//     name: 'Noodle in a Haystack',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/BoEM-6j0592nJhFGHMu-jA/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/noodle-in-a-haystack-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 52,
//     categories: [
//       {
//         alias: 'ramen',
//         title: 'Ramen',
//       },
//       {
//         alias: 'newamerican',
//         title: 'American (New)',
//       },
//     ],
//     rating: 5.0,
//     coordinates: {
//       latitude: 37.78066412799114,
//       longitude: -122.46872181182351,
//     },
//     transactions: [],
//     price: '$$',
//     location: {
//       address1: '4601 Geary Blvd',
//       address2: '',
//       address3: '',
//       city: 'San Francisco',
//       zip_code: '94118',
//       country: 'US',
//       state: 'CA',
//       display_address: ['4601 Geary Blvd', 'San Francisco, CA 94118'],
//     },
//     phone: '',
//     display_phone: '',
//     distance: 3588.5283928892763,
//   },
//   {
//     id: 'UYNswbdsQ5OvwnyY9esxCw',
//     alias: 'wooden-spoon-san-francisco',
//     name: 'Wooden Spoon',
//     image_url:
//       'https://s3-media4.fl.yelpcdn.com/bphoto/JHujNEsKp9ZvzHQazdVOCQ/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/wooden-spoon-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 516,
//     categories: [
//       {
//         alias: 'breakfast_brunch',
//         title: 'Breakfast & Brunch',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.7666182758937,
//       longitude: -122.430262778253,
//     },
//     transactions: ['delivery'],
//     price: '$$',
//     location: {
//       address1: '2172 Market St',
//       address2: '',
//       address3: null,
//       city: 'San Francisco',
//       zip_code: '94114',
//       country: 'US',
//       state: 'CA',
//       display_address: ['2172 Market St', 'San Francisco, CA 94114'],
//     },
//     phone: '+14159463005',
//     display_phone: '(415) 946-3005',
//     distance: 828.0966364921373,
//   },
//   {
//     id: 'PRLdyVFYxgJ6z_D-BSM5kQ',
//     alias: 'scott-s-chowder-house-san-francisco',
//     name: 'Scott’s Chowder House',
//     image_url:
//       'https://s3-media2.fl.yelpcdn.com/bphoto/3CYUxG2AeQY7uZEs2WBIOg/o.jpg',
//     is_closed: false,
//     url: 'https://www.yelp.com/biz/scott-s-chowder-house-san-francisco?adjust_creative=tYgyg1YJcI4gIavcvsxPNw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=tYgyg1YJcI4gIavcvsxPNw',
//     review_count: 13,
//     categories: [
//       {
//         alias: 'seafood',
//         title: 'Seafood',
//       },
//       {
//         alias: 'soup',
//         title: 'Soup',
//       },
//     ],
//     rating: 4.5,
//     coordinates: {
//       latitude: 37.78166,
//       longitude: -122.43265,
//     },
//     transactions: ['delivery', 'pickup'],
//     location: {
//       address1: '1325 Fillmore St',
//       address2: '',
//       address3: null,
//       city: 'San Francisco',
//       zip_code: '94115',
//       country: 'US',
//       state: 'CA',
//       display_address: ['1325 Fillmore St', 'San Francisco, CA 94115'],
//     },
//     phone: '+16282014567',
//     display_phone: '(628) 201-4567',
//     distance: 2365.8361120544328,
//   },
// ];
